# These are supported funding model platforms

github: solomonrajan
patreon: # Replace with a single Patreon username
open_collective: solomonrajan
ko_fi: solomonrajan
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: solomon.rajan
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
custom: https://www.buymeacoffee.com/solomonrajan
